run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gosec
    - unconvert
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gosec:
    excludes:
      - G204 # Subprocess launched with variable
      - G304 # File path provided as taint input

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

issues:
  exclude-rules:
    - path: test
      linters:
        - gosec
        - errcheck
    - path: _test\.go
      linters:
        - gosec
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0
