apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odin.fullname" . }}-secrets
  labels:
    {{- include "odin.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- range $provider, $secret := .Values.secrets.oauth2ClientSecrets }}
  oauth2-{{ $provider }}-secret: {{ $secret | b64enc | quote }}
  {{- end }}
