global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'odin'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['odin:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - 'alertmanager:9093'  # Uncomment if you have alertmanager
