apiVersion: apps/v1
kind: Deployment
metadata:
  name: odin-api-gateway
  labels:
    app: odin-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odin-api-gateway
  template:
    metadata:
      labels:
        app: odin-api-gateway
    spec:
      containers:
        - name: odin-api-gateway
          image: odin-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: admin
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: '1'
              memory: '1Gi'
            requests:
              cpu: '500m'
              memory: '512Mi'
          volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: LOG_LEVEL
              value: 'info'
            - name: ODIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: odin-secrets
                  key: jwt-secret
      volumes:
        - name: config
          configMap:
            name: odin-config
