apiVersion: v1
kind: Service
metadata:
  name: odin-api-gateway
spec:
  selector:
    app: odin-api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: admin
      port: 8081
      targetPort: 8081
  type: ClusterIP
